[package]
name = "ddapi-rs"
description = "This module is rewritten from another module [ddapi](https://github.com/ByFox213/ddapi)"
version = "0.7.0"
edition = "2021"
repository = "https://github.com/ByFox213/ddapi-rs"
license = "MIT"
readme = "README.md"
keywords = ["ddnet", "ddstats", "api"]

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_derive = "1.0.215"
urlencoding = "2.1.3"
chrono = "0.4.41"
anyhow = "1.0.98"
moka = { version = "0.12.10", features = ["log", "future"] }

[features]
default = ["ddnet"]
ddnet = []
ddstats = []
cache = []
full = ["ddnet", "ddstats", "cache"]
